Repository cloudfuse-io/lambdatization, pull requests merged in 2022-10, with the labels that each got.

#22 Dremio in lambda
  README.md
  cli/plugins/dremio.py
  infra/dremio/.terraform.lock.hcl
  infra/dremio/build/Dockerfile
  infra/dremio/build/README.md
  infra/dremio/build/docker-compose.yaml
  infra/dremio/build/dremio-env
  infra/dremio/build/dremio.conf
  infra/dremio/build/lambda-handler.py
  infra/dremio/main.tf
  infra/dremio/terragrunt.hcl
  infra/spark/build/lambda-handler.py
Labels: Feature

#24 Run images locally and test builds in CI
  .github/workflows/l12n.yaml
  cli/common.py
  cli/core.py
  cli/plugins/dremio.py
  cli/plugins/spark.py
  infra/dremio/build/docker-compose.yaml
  infra/dremio/build/lambda-handler.py
  infra/spark/build/docker-compose.yaml
  infra/spark/build/lambda-handler.py
Labels: Feature

#25 Describe basic CMDs and configs
  README.md
Labels: Documentation

#33 fix black
  .github/workflows/style-check.yaml
Labels: Bug

#29 Error handling
  cli/common.py
  cli/core.py
Labels: Improvement

#36 Feat(Dask): first version
  cli/main.py
  cli/plugins/dask.py
  cli/plugins/monitoring.py
  cli/plugins/spark.py
  infra/runtime/dask/.terraform.lock.hcl
  infra/runtime/dask/build/Dockerfile
  infra/runtime/dask/build/README.md
  infra/runtime/dask/build/docker-compose.yaml
  infra/runtime/dask/build/lambda-handler.py
  infra/runtime/dask/main.tf
  infra/runtime/dask/terragrunt.hcl
Labels: Feature

#40 Imp(spark): reuse the sql cli
  cli/plugins/spark.py
  infra/runtime/spark/build/Dockerfile
  infra/runtime/spark/build/lambda-handler.py
Labels: Improvement

#41 Imp(engines): cleanup scripts and docs
  cli/core.py
  infra/runtime/README.md
  infra/runtime/dask/build/docker-compose.yaml
  infra/runtime/dask/build/lambda-handler.py
  infra/runtime/databend/build/Dockerfile
  infra/runtime/databend/build/docker-compose.yaml
  infra/runtime/databend/build/lambda-handler.py
  infra/runtime/dremio/build/Dockerfile
  infra/runtime/dremio/build/docker-compose.yaml
  infra/runtime/dremio/build/lambda-handler.py
  infra/runtime/spark/build/Dockerfile
  infra/runtime/spark/build/README.md
  infra/runtime/spark/build/docker-compose.yaml
  infra/runtime/spark/build/lambda-handler.py
Labels: Improvement

#42 Fix(engines): dockerized broken
  infra/runtime/dask/build/lambda-handler.py
  infra/runtime/databend/build/lambda-handler.py
  infra/runtime/dremio/build/lambda-handler.py
  infra/runtime/spark/build/lambda-handler.py
Labels: Bug
