Repository cloudfuse-io/lambdatization, pull requests merged in 2022-11, with the labels that each got.

#44 CI(trino): first attempt for build
  .github/workflows/trino.yaml
Labels: Feature

#46 CI(trino): fix workdir
  .github/workflows/trino.yaml
Labels: Bug

#48 Feat(ci): hadoop mirroring
  .github/workflows/hadoop.yaml
Labels: Improvement

#49 imp(ci): make image builds parallel
  .github/workflows/l12n.yaml
Labels: Improvement

#43 Feat(trino): first version
  .github/workflows/style-check.yaml
  .github/workflows/trino.yaml
  cli/core.py
  cli/plugins/monitoring.py
  cli/plugins/trino.py
  infra/runtime/dremio/build/README.md
  infra/runtime/trino/.terraform.lock.hcl
  infra/runtime/trino/build/Dockerfile
  infra/runtime/trino/build/README.md
  infra/runtime/trino/build/docker-compose.yaml
  infra/runtime/trino/build/lambda-handler.py
  infra/runtime/trino/build/metastore-site.xml
  infra/runtime/trino/build/trino-etc/catalog/hive.properties
  infra/runtime/trino/build/trino-etc/config.properties
  infra/runtime/trino/build/trino-etc/jvm.config
  infra/runtime/trino/build/trino-etc/node.properties
  infra/runtime/trino/main.tf
  infra/runtime/trino/terragrunt.hcl
Labels: Feature

#50 Fix(ci): missing engines
  .github/workflows/l12n.yaml
  README.md
Labels: Bug

#51 Fix(doc): broken link
  README.md
Labels: Bug

#52 Imp: improve main readme
  README.md
Labels: Documentation

#53 Feat(CI): add ballista build
  .github/workflows/ballista.yaml
Labels: Improvement

#55 fix: ballista CI
  .github/workflows/ballista.yaml
  .github/workflows/semantic-pr.yaml
Labels: Bug

#32 feat(Ballista): include docker image for lambda
  .github/workflows/l12n.yaml
  cli/plugins/ballista.py
  cli/plugins/monitoring.py
  infra/runtime/ballista/.terraform.lock.hcl
  infra/runtime/ballista/build/Dockerfile
  infra/runtime/ballista/build/README.md
  infra/runtime/ballista/build/docker-compose.yaml
  infra/runtime/ballista/build/lambda-handler.py
  infra/runtime/ballista/main.tf
  infra/runtime/ballista/terragrunt.hcl
Labels: Feature

#56 docs: specify types for PR titles
  README.md
Labels: Documentation

#57 fix(monitoring): empty error message
  cli/plugins/monitoring.py
Labels: Bug

#59 ci(clickhouse): build ci init
  .github/workflows/clickhouse.yaml
Labels: Feature

#60 ci(clickhouse): fix build
  .github/gh-runner-setup.sh
  .github/workflows/clickhouse.yaml
Labels: Bug

#63 fix(cli): user discrepency when runnin on different host
  .github/workflows/l12n.yaml
  README.md
  cli.Dockerfile
  cli/core.py
  cli/docker/Dockerfile
  cli/docker/entrypoint.sh
  l12n-shell
Labels: Bug

#61 ci: fix image tags
  .github/workflows/clickhouse.yaml
  .github/workflows/l12n.yaml
  infra/runtime/clickhouse/build/Dockerfile
Labels: Improvement

#62 feat(monitoring): add scaling infra and dashboard
  cli/core.py
  cli/plugins/monitoring.py
  cli/plugins/scaling.py
  docs/scaling_metrics.md
  docs/standalone_engine_metrics.md
  infra/monitoring/bigquery/main.tf
  infra/runtime/scaling/.terraform.lock.hcl
  infra/runtime/scaling/build/Dockerfile
  infra/runtime/scaling/build/docker-compose.yaml
  infra/runtime/scaling/build/lambda-handler.py
  infra/runtime/scaling/main.tf
  infra/runtime/scaling/terragrunt.hcl
Labels: Feature

#65 ci: improve speed
  .github/workflows/engines.yaml
  .github/workflows/l12n.yaml
  l12n-shell
Labels: Improvement

#66 fix: broken badge
  README.md
Labels: Bug, Documentation

#67 ci: improve ci struct
  .github/workflows/engines.yaml
  .github/workflows/helper-ballista.yaml
  .github/workflows/helper-clickhouse.yaml
  .github/workflows/helper-hadoop.yaml
  .github/workflows/helper-trino.yaml
  .github/workflows/labels.yaml
  README.md
  infra/runtime/clickhouse/build/README.md
  infra/runtime/trino/build/README.md
Labels: Improvement

#68 docs: update docstring
  infra/runtime/ballista/build/lambda-handler.py
  infra/runtime/clickhouse/build/lambda-handler.py
  infra/runtime/dask/build/lambda-handler.py
  infra/runtime/databend/build/lambda-handler.py
  infra/runtime/dremio/build/lambda-handler.py
  infra/runtime/spark/build/lambda-handler.py
  infra/runtime/trino/build/lambda-handler.py
Labels: Documentation
